#!/bin/sh

#todo: read first argument for context of build
#todo: add switch to go into bash at build

#todo: add timestamp + rand as a variable
timestamp="$(date +%s)"
docker build -t test-tmp-$timestamp . && docker run --name test-tmp-$timestamp -it test-tmp-$timestamp
docker rm test-tmp-$timestamp > /dev/null 2>&1
docker rmi test-tmp-$timestamp > /dev/null 2>&1
